version: '3.4'

services:
  onlinecourse:
    image: ${DOCKER_REGISTRY}onlinecourse
    build:
      context: .
      dockerfile: OnlineCourse\Dockerfile

  gateway:
    image: ${DOCKER_REGISTRY}gateway
    build:
      context: .
      dockerfile: ..\GateWay\Dockerfile

